### ISSUE TITLE
Menu: SellerDashboard does not work on first click

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/bnp#125]
Login as supplier user and select  Company -> Profile:

![grafik](https://user-images.githubusercontent.com/26661092/28672447-15655fda-72e0-11e7-9c3a-3414e35f9cde.png)

The link seems to be ok, but when selecting it a wrong URL is called.

![grafik](https://user-images.githubusercontent.com/26661092/28672697-bc79decc-72e0-11e7-8e55-975b6f8d45d6.png)

Only when selecting it a second time the supplier editor is shown.

**Comment by celber** [comment]
waits for https://github.com/OpusCapita/react-components/pull/11

**Comment by lasong** [comment]
Fixed by OpusCapita/react-components#11

**Comment by lasong** [comment]
Still not working

**Comment by lasong** [comment]
Still not working :(

**Comment by nczeranka** [comment]
see also OpusCapita/onboarding#346

**Comment by lasong** [comment]
Working now
