### ISSUE TITLE
Invoice Connections widget / management view 

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#132]
On supplier dashboard
Below the eInvoice Connected indicator, please place some details
example: (25 Connections)
and a button next to it that allows viewing the list of connected customers.

This should link to a UI under menu Invoice/Manage Connections
where we would list all connected customers in a table
including customerId, customerName, createdOn, status, actions

We should have a disabled button for "Add Connection" (and show sth like Coming Soon as mouseover)

**Comment by lasong** [comment]
Duplicate to https://github.com/OpusCapita/bnp/issues/179
