### ISSUE TITLE
SellerDashboard & IE11: Status not up-to-date properly

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/bnp#135]
How to reproduce:
- Use an IE11
- Register a new supplier (to have a clean status)
- Go to InChannelConfig and finish the configuration.
- Then SellerDashboard is opened automatically, but shows the state 'Connecting'.

Only a hard Reload of the page (F5) of the user changed the state to 'Connected'.

It worked for Firefox and Chrome! 
Edge was not tested up to now, due to CSS problems with the check boxes/radio buttons.

**Comment by nczeranka** [comment]
To clean the Config for a specific supplier - here 'oc04', you can use following SQL statements:
delete from `einvoice-send`.InChannelConfig where supplierId = 'oc04';
delete from `einvoice-send`.PdfChannelConfig where supplierId = 'oc04';
delete from `einvoice-send`.PaperChannelConfig where supplierId = 'oc04';
delete from `einvoice-send`.EInvoiceChannelConfig where supplierId = 'oc04';
delete from `einvoice-send`.InChannelContract where supplierId = 'oc04';

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/bnp/commit/afff2e8cd4895071fd97159c110258bac2180c50
