### ISSUE TITLE
CSS: welcome page has bad representation under small screens

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/bnp#141]
The page `/bnp/welcome` is not working properly under small sized screens/windows. I.e. the Start button is not visible or reachable, since the page is not scrollable, whereas the button is under the bottom.
![30801236-ebba2f30-a1e2-11e7-9c62-ee77a5237519](https://user-images.githubusercontent.com/11177808/30802259-29b2aaa8-a1e6-11e7-9605-a6b7fb05f5f4.png)

**Comment by lasong** [comment]
@kekonen does this still happen with new UI layout?

**Comment by kekonen** [comment]
@lasong It looks fine now
