### ISSUE TITLE
Add user administration 

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#146]
Should be in menu Administration/Users
Visible to both buyers, suppliers.

Use shared component from user service.

**Comment by gr4per** [comment]
implements: https://github.com/OpusCapita/businessnetwork/issues/87
see also https://github.com/OpusCapita/user/issues/81

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/bnp/pull/151 and https://github.com/OpusCapita/bnp/pull/162
