### ISSUE TITLE
Replace old Invoice Sending Configuration with new one

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/bnp#178]
depends on OpusCapita/einvoice-send/issues/156

---

Replace links to the invoice sending configuration from the old on
 - https://develop.businessnetwork.opuscapita.com/einvoice-send

to the new one
- https://develop.businessnetwork.opuscapita.com/einvoice-send/customer-connections

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/bnp/commit/a9c3572289392ff071dadebf62ca9035a315df5b

**Comment by nczeranka** [comment]
![grafik](https://user-images.githubusercontent.com/26661092/41229402-274d3de8-6d7c-11e8-99f5-91aaf3238ae8.png)

**Comment by lasong** [comment]
Done https://github.com/OpusCapita/bnp/commit/9bf6dee2c450cbaa832feb1fe94800b2af142a80
