### ISSUE TITLE
Create isodata service

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#55]
Implement service with API to allow access to static base data
-currencies
-countries
-langauges

 Can be stored as json, no need for db tables
API can be limited to list, e.g. GET /isodata/v1/currencies
We dont need to support individual resource ids or even POST/PATCH/DELETE/PUT

https://docs.google.com/document/d/1EeC37uyBHuoXX9WOQ175XtWciya-tXbavDKCq6qUiTo/edit

**Comment by celber** [comment]
https://github.com/OpusCapitaBusinessNetwork/isodata
