### ISSUE TITLE
BNP menu items are broken

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#73]
![image](https://cloud.githubusercontent.com/assets/22681804/25372216/c55cae60-2994-11e7-93b6-d48d3c2826bf.png)

All the menu items in Supplier menu point to campaigns instead of onboarding and thus are broken links.

**Comment by gr4per** [comment]
Also
![image](https://cloud.githubusercontent.com/assets/22681804/25432069/5e50b06e-2a83-11e7-8cef-6dd7a03f6692.png)

Please make sure to test every menu item...

**Comment by patrykkopycinski** [comment]
@gr4per should be fine now
