### ISSUE TITLE
Translation assist

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#95]
Write helper script that does
traverse src/client/components and each i18n bundle in there
collect all keys and generate result csv like follows
| path to i18n folder | en translation | de translation |

Later we will use it to manually correct the translation

And then we need another script parsing the csv and updating the respective bundles

script to be runnable via npm (so define in package json as targets)

**Comment by gr4per** [comment]
mayank what about this?
I know we got script to find/excel export translations, but what about re-importing?
Do we have a place where this process is documented ?

**Comment by mayank-cronj** [comment]
Implemented at 
https://github.com/OpusCapita/i18n-assist

Need to integrate with the services

**Comment by lasong** [comment]
See  https://github.com/OpusCapita/i18n-assist
