### ISSUE TITLE
Buyer dashboard

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/bnp#99]
1) Integrate eTransition funnel chart from onbaording
DependsOn:https://github.com/OpusCapita/businessnetwork/issues/11

2) Integrate eTransition today chart from onboarding (Recent campaigns stacked column chart, this is top right one on onboarding dashboard)

3) Hide top left and bottem left charts for now

**Comment by lasong** [comment]
Point 2 implemented with https://github.com/OpusCapita/bnp/pull/126

Card is now done
